version: '3.2'

services:

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: pasquale
      MYSQL_USER: phabricator
      MYSQL_PASSWORD: phabricator
      MYSQL_DATABASE: phabricator
      # MYSQL_ROOT_HOST: 172.19.0.3
    volumes:
      - type: bind
        source: ~/docker/phabricator/phabricator/data
        target: /var/lib/mysql

  phabricator:
    # images was: redpointgames/phabricator. Modificato dopo il commit
    # image: redpointgames/phabricator
    image: p
    # image: paskaly/phabricatory
    container_name: pha
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 80:80
      - 443:443
      - 22:22

    environment:
      MYSQL_HOST: mysql
      # MYSQL_LINKED_CONTAINER: mysql
      MYSQL_USER: root
      MYSQL_PASS: pasquale
      PHABRICATOR_HOST: pasquale.com
      PHABRICATOR_REPOSITORY_PATH: /repos
      PHABRICATOR_STORAGE_TYPE: disk
      PHABRICATOR_STORAGE_PATH: /files

    volumes:
      - type: bind
        source: ~/docker/phabricator/phabricator/repository
        target: /repos
      - type: bind
        source: ~/docker/phabricator/phabricator/files
        target: /files
      - type: bind
        source: ~/docker/phabricator/phabricator/extensions
        target: /srv/phabricator/phabricator/src/extensions
      - type: bind
        source: ~/docker/phabricator/config
        target: /config
