version: '3.2'

services:

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: pasquale
      MYSQL_USER: phabricator
      MYSQL_PASSWORD: phabricator
      MYSQL_DATABASE: phabricator
      # MYSQL_ROOT_HOST: 172.19.0.3
    volumes:
      - type: bind
        source: ~/docker/phabry/data
        target: /var/lib/mysql
      - type: bind
        source: ~/docker/phabry/dataconf
        target: /etc/mysql/conf.d

  phabricator:
    image: phabry
    container_name: phabry
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 80:80
      - 443:443
      - 22:22

    environment:
      MYSQL_HOST: mysql
      # MYSQL_LINKED_CONTAINER: mysql
      MYSQL_USER: root
      MYSQL_PASS: pasquale
      PHABRICATOR_HOST: f.sublogica.com
      PHABRICATOR_REPOSITORY_PATH: /repos
      PHABRICATOR_STORAGE_TYPE: disk
      PHABRICATOR_STORAGE_PATH: /files

    volumes:
      - type: bind
        source: ~/docker/phabry/repository
        target: /repos
      - type: bind
        source: ~/docker/phabry/files
        target: /files
      - type: bind
        source: ~/docker/phabry/extensions
        target: /srv/phabricator/phabricator/src/extensions
      - type: bind
        source: ~/docker/phabry/config
        target: /config
      - type: bind
        source: ~/docker/phabry/srv
        target: /srv

